version: "3.8"

services:
  fintafsir-app:
    build: .
    ports:
      - "64829:64829"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    container_name: fintafsir_container
